services:
  db:
    build: db

  sequenceserver:
    build: .
    volumes_from: ["db"]
    restart: always
    healthcheck:
      test: curl -qo /dev/null http://localhost:4567/searchdata.json
    ports:
      - "4568:4567"
